
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter-openstack-provider
  namespace: karpenter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karpenter-openstack-provider
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["karpenter.sh", "karpenter.k8s.openstack"]
    resources: ["openstacknodeclasses", "nodeclaims"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["karpenter.sh"]
    resources: ["nodepools"]
    verbs: ["get", "list", "watch", "patch", "update"]

  - apiGroups: ["karpenter.sh"]
    resources: ["nodepools/status"]
    verbs: ["patch", "update"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpenter-openstack-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: karpenter-openstack-provider
subjects:
- kind: ServiceAccount
  name: karpenter-openstack-provider
  namespace: karpenter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-openstack-provider
  namespace: karpenter
  labels:
    app: karpenter-openstack-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karpenter-openstack-provider
  template:
    metadata:
      labels:
        app: karpenter-openstack-provider
    spec:
      serviceAccountName: karpenter-openstack-provider
      containers:
      - name: provider
        image: ianzx15/karpenter-openstack-provider:latest
        imagePullPolicy: Always

        envFrom:
        - secretRef:
            name: os-env-vars

        env:
        - name: CLUSTER_NAME
          value: "kubernetes"
        - name: RUN_INTEGRATION_TESTS
          value: "1"
        - name: LEADER_ELECTION_NAMESPACE
          value: "kube-system"
        - name: KUBERNETES_MIN_VERSION
          value: "1.19.0"
        - name: KARPENTER_SERVICE
          value: "karpenter"
        - name: LOG_LEVEL
          value: "debug"
        - name: DISABLE_WEBHOOK
          value: "true"

        volumeMounts:
        - name: cloud-config
          mountPath: /etc/openstack
          readOnly: true

      volumes:
      - name: cloud-config
        secret:
          secretName: openstack-cloud-config
          items:
          - key: cloud.yaml
            path: clouds.yaml
