---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: karpenter-openstack-provider
  namespace: karpenter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: karpenter-openstack-provider
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["karpenter.sh", "karpenter.k8s.openstack"]
    resources: ["openstacknodeclasses", "nodeclaims"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["karpenter.sh"]
    resources: ["nodepools"]
    verbs: ["get", "list", "watch", "patch", "update"]

  - apiGroups: ["karpenter.sh"]
    resources: ["nodepools/status"]
    verbs: ["patch", "update"]
  
  - apiGroups: ["karpenter.sh"] 
    resources: ["nodeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
  - apiGroups: ["karpenter.sh"]
    resources: ["nodeclaims/status"]
    verbs: ["get", "update", "patch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments", "csinodes"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch"]
  
  - apiGroups: ["karpenter.k8s.openstack"]
    resources: ["openstacknodeclasses"]
    verbs: ["get", "list", "watch", "update", "patch"] 

  - apiGroups: ["karpenter.k8s.openstack"]
    resources: ["openstacknodeclasses/status"]
    verbs: ["get", "update", "patch"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: karpenter-openstack-provider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: karpenter-openstack-provider
subjects:
  - kind: ServiceAccount
    name: karpenter-openstack-provider
    namespace: karpenter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-openstack-provider
  namespace: karpenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karpenter-openstack-provider
  template:
    metadata:
      labels:
        app: karpenter-openstack-provider
    spec:
      serviceAccountName: karpenter-openstack-provider
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoExecute"
      containers:
      - name: provider
        image: ianzx15/karpenter-openstack-provider:latest
        imagePullPolicy: Always
        args:
        - "-disable-leader-election"
        env:
        - name: KARPENTER_SERVICE
          value: "karpenter"
        - name: LOG_LEVEL
          value: "debug"
        - name: DISABLE_WEBHOOK
          value: "true"
        - name: CLUSTER_NAME
          value: "karpenter-cluster"
        - name: KUBERNETES_MIN_VERSION
          value: "1.19.0"
        - name: LOG_LEVEL
          value: "info" 
        envFrom:
        - secretRef:
            name: os-env-vars
