apiVersion: v1
kind: Secret
metadata:
  name: karpenter-openstack-credentials
  namespace: karpenter-system
type: Opaque
stringData:
  cloud.conf: |
    [Global]
    # Auth URL of your OpenStack Identity service
    auth-url = <your-openstack-auth-url>
    # Username of the service account
    username = <your-username>
    # Password for the service account
    password = <your-password>
    # Project (tenant) name
    tenant-name = <your-project-name>
    # Project (tenant) domain name
    domain-name = <your-domain-name>
    # Region
    region = <your-region>
